---
name: Container Build for Tag
on:
  push:
    tags: '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set Tag
        id: tag
        run: |
          docker_tag=$(echo "${{ github.ref }}" | awk -F / '{print $NF}')
          echo "::set-output name=name::$docker_tag"
      - name: Docker login (Docker Hub)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/image-hashes:${{ steps.tag.outputs.name }}
