---
name: Smoke
on:
  push:
  pull_request:
  schedule:
    - cron: '0 13 * * *'

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
